[pytest]
minversion = 6.0
addopts = -ra -q --cov=/../tick_data_downloader --cov-report=term-missing
testpaths = 
    tests
python_files = test_*.py
markers =
    asyncio: mark test to run in asyncio event loop
